# В данном файле рассмотрены базовые методы для работы с массивами в numpy #

In [1]:
#1. импорт библиотеки
import numpy as np

In [29]:
#2. Создание массивов
arr = np.array([1, 2, 3, 4])  
print(f"\nПростой массив:\n{arr}")

arr_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\nПростой двумерный массив:\n{arr_d}")

arr_zeros = np.zeros(5,  dtype=int)
print(f"\nМассив из нулей:\n{arr_zeros}")

arr_zeros_d = np.zeros((2, 3))
print(f"\nДвумерный массив из нулей:\n{arr_zeros_d}")

arr_ones = np.ones(5,  dtype=int)
print(f"\nМассив из единиц:\n{arr_ones}")

arr_ones_d = np.ones((2, 3))
print(f"\nДвумерный массив из единиц:\n{arr_ones_d}")

arr_arange = np.arange(2,5)
print(f"\nСоздание массива из чисел от 2 до 4:\n{arr_arange}")

arr_step = np.arange(1, 100, 24)
print(f"\nМассив с шагом 24:\n{arr_step}")

arr_random = np.random.random((2, 3))
print(f"\nМассив случайных чисел:\n{arr_random}")

arr_1d = np.arange(12)
print(f"\nОдномерный массив:\n {arr_1d}")
# Преобразуем в двумерный массив 3x4
arr_2d = arr_1d.reshape(3, 4)
print(f"\nДвумерный массив 3x4:\n{arr_2d}")


Простой массив:
[1 2 3 4]

Простой двумерный массив:
[[1 2 3 4]
 [5 6 7 8]]

Массив из нулей:
[0 0 0 0 0]

Двумерный массив из нулей:
[[0. 0. 0.]
 [0. 0. 0.]]

Массив из единиц:
[1 1 1 1 1]

Двумерный массив из единиц:
[[1. 1. 1.]
 [1. 1. 1.]]

Создание массива из чисел от 2 до 4:
[2 3 4]

Массив с шагом 24:
[ 1 25 49 73 97]

Массив случайных чисел:
[[0.76014512 0.08120261 0.56268691]
 [0.15722113 0.05330005 0.74604259]]

Одномерный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Двумерный массив 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
#3. Демонстрация атрибутов
print("Форма и тип данных для массива arr_zeros_d:")
print(f"shape: {arr_zeros_d.shape}")
print(f"dtype: {arr_zeros_d.dtype}")

Форма и тип данных для массива arr_zeros_d:
shape: (2, 3)
dtype: float64


In [34]:
#4. Индексирование и срезы
print(f"Элемент массива arr_step по индексу 4: {arr_step[4]}")
print(f"Срез  элементов от 1 до 4 (не включительно): {arr_step[1:4]}")

#для двумерного массива
print(f"\nЭлемент в строке 1, столбце 3: {arr_2d[1, 3]}")  # так как считаем с 0, в привычном счёте это строка 2, столбец 4
print(f"\nСрез первых трёх строк:\n{arr_2d[0:3]}")
print(f"\nСрез столбцов 1-2 во всех строках:\n{arr_2d[:, 1:3]}")
print(f"\nСрез: первые 2 строки, столбцы 1-2:\n{arr_2d[0:2, 1:3]}")

Элемент массива arr_step по индексу 4: 97
Срез  элементов от 1 до 4 (не включительно): [25 49 73]

Элемент в строке 1, столбце 3: 7

Срез первых трёх строк:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Срез столбцов 1-2 во всех строках:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Срез: первые 2 строки, столбцы 1-2:
[[1 2]
 [5 6]]


In [43]:
#5. Примеры векторных операций и базовых статистик
arr_f = np.arange(10)
scalar = 4
print(f"Массив: {arr_f}")
print(f"Сложение массива со скаляром: {arr_f + scalar}")
print(f"Вычитание скаляра из массива: {arr_f - scalar}")
print(f"Умножение массива на скаляр: {arr_f * scalar}")
print(f"Деление массива на скаляр: {arr_f / scalar}")
print(f"Возведение в степень: {arr_f ** scalar}")

Массив: [0 1 2 3 4 5 6 7 8 9]
Сложение массива со скаляром: [ 4  5  6  7  8  9 10 11 12 13]
Вычитание скаляра из массива: [-4 -3 -2 -1  0  1  2  3  4  5]
Умножение массива на скаляр: [ 0  4  8 12 16 20 24 28 32 36]
Деление массива на скаляр: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
Возведение в степень: [   0    1   16   81  256  625 1296 2401 4096 6561]


In [42]:
# для двумерных массивов
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Массив A:\n", A)
print("Массив B:\n", B)
print(f"Поэлементное сложение:\n{A + B}")
print(f"Поэлементное вычитание:\n{A - B}")
print(f"Поэлементное умножение:\n{A * B}")
print(f"Поэлементное деление:\n{A / B}")
print(f"Поэлементное возведение в степень:\n{A ** B}\n")

Массив A:
 [[1 2]
 [3 4]]
Массив B:
 [[5 6]
 [7 8]]
Поэлементное сложение:
[[ 6  8]
 [10 12]]
Поэлементное вычитание:
[[-4 -4]
 [-4 -4]]
Поэлементное умножение:
[[ 5 12]
 [21 32]]
Поэлементное деление:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Поэлементное возведение в степень:
[[    1    64]
 [ 2187 65536]]



In [45]:
# Статистика
print(f"Среднее значение в A: {A.mean()}")
print(f"Сумма всех элементов в A: {A.sum()}")
print(f"Стандартное отклонение в A: {A.std():.2f}")  # округление до 2 знаков

# Статистика по осям 
print(f"Среднее по строкам (axis=1): {A.mean(axis=1)}")
print(f"Среднее по столбцам (axis=0): {A.mean(axis=0)}")

Среднее значение в A: 2.5
Сумма всех элементов в A: 10
Стандартное отклонение в A: 1.12
Среднее по строкам (axis=1): [1.5 3.5]
Среднее по столбцам (axis=0): [2. 3.]
